### ISSUE TITLE
请问25日下午的课程有没有？

### ISSUE THREAD

**Issue by hidoopos** [ArlanCooper/-#2]
表示存储，查询检索这块也很重要

**Comment by ArlanCooper** [comment]
有点大，4个G以上，我放不到云盘，需要压缩一下，稍等

**Comment by hidoopos** [comment]
> 有点大，4个G以上，我放不到云盘，需要压缩一下，稍等

嗯，可能按照课程的课时切分下就不会这么大了。B站也有人上传，看了也是不全

**Comment by ArlanCooper** [comment]
25日下午的已经放上去了，如果你有26日下午的，可以分享出来，不胜感激

**Comment by hidoopos** [comment]
> 25日下午的已经放上去了，如果你有26日下午的，可以分享出来，不胜感激

https://space.bilibili.com/367133208 好像这位up上传了

**Comment by ArlanCooper** [comment]
> > 25日下午的已经放上去了，如果你有26日下午的，可以分享出来，不胜感激
> 
> https://space.bilibili.com/367133208 好像这位up上传了

谢谢
